sudo: false

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^quorbita-.*$/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/

install: /bin/true

script: gradle check

after_success: gradle bintrayUpload
